"""init

Revision ID: 78800c13b80d
Revises: 
Create Date: 2026-01-08 14:45:02.605906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78800c13b80d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('idEmpleado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('sueldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('idEmpleado')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleados')
    # ### end Alembic commands ###
